### GET request to simple server created by FilterServer
GET http://localhost:8080/simple/
# expect 200 + contents of 'index.html'
###

### GET request to simple server
GET http://localhost:8080/simple/index.html
# expect 200 + contents of 'index.html'
###

### PATCH request to example server
POST http://localhost:8080/simple
# expect 405 Method Not Allowed
###